#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Script generated by Vivado on Wed Jun 28 06:03:16 PDT 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# Tool Version Limit: 2023.05 
#
# Filename     : design_1.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : design_1.sh
#                design_1.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                design_1.sh [-reset_run]
#                design_1.sh [-reset_log]
#                design_1.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the Xilinx simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'design_1.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xil_defaultlib -libname microblaze_v11_0_11 -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_13 -libname lmb_v10_v3_0_12 -libname lmb_bram_if_cntlr_v4_0_22 -libname blk_mem_gen_v8_4_6 -libname iomodule_v3_1_8 -libname axi_lite_ipif_v3_0_4 -libname lib_pkg_v1_0_2 -libname lib_srl_fifo_v1_0_2 -libname axi_uart16550_v2_0_30 -libname generic_baseblocks_v2_1_0 -libname axi_infrastructure_v1_1_0 -libname axi_register_slice_v2_1_28 -libname fifo_generator_v13_2_8 -libname axi_data_fifo_v2_1_27 -libname axi_crossbar_v2_1_29 -libname axi_bram_ctrl_v4_1_8 -libname dist_mem_gen_v8_0_13 -libname lib_fifo_v1_0_17 -libname interrupt_control_v3_1_4 -libname axi_quad_spi_v3_2_27 -libname axi_clock_converter_v2_1_27 -libname axi_protocol_converter_v2_1_28 -libname axi_dwidth_converter_v2_1_28 -libname axi_mmu_v2_1_26 -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xil_defaultlib microblaze_v11_0_11 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 lmb_v10_v3_0_12 lmb_bram_if_cntlr_v4_0_22 blk_mem_gen_v8_4_6 iomodule_v3_1_8 axi_lite_ipif_v3_0_4 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uart16550_v2_0_30 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_28 fifo_generator_v13_2_8 axi_data_fifo_v2_1_27 axi_crossbar_v2_1_29 axi_bram_ctrl_v4_1_8 dist_mem_gen_v8_0_13 lib_fifo_v1_0_17 interrupt_control_v3_1_4 axi_quad_spi_v3_2_27 axi_clock_converter_v2_1_27 axi_protocol_converter_v2_1_28 axi_dwidth_converter_v2_1_28 axi_mmu_v2_1_26)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2023.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
  "../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvhdl -work microblaze_v11_0_11 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/e224/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_0/sim/bd_0eaf_microblaze_I_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_13 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_1/sim/bd_0eaf_rst_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_v10_v3_0_12 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/cd1d/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_2/sim/bd_0eaf_ilmb_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_3/sim/bd_0eaf_dlmb_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lmb_bram_if_cntlr_v4_0_22 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/b87e/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_4/sim/bd_0eaf_dlmb_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_5/sim/bd_0eaf_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work blk_mem_gen_v8_4_6 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_6/sim/bd_0eaf_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_7/sim/bd_0eaf_second_dlmb_cntlr_0.vhd" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_8/sim/bd_0eaf_second_ilmb_cntlr_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_9/sim/bd_0eaf_second_lmb_bram_I_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work iomodule_v3_1_8 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/b8f2/hdl/iomodule_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/ip/ip_10/sim/bd_0eaf_iomodule_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/bd_0/sim/bd_0eaf.v" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_0/sim/design_1_ddr3_0_0_microblaze_mcs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/phy/design_1_ddr3_0_0_phy_ddr3.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/phy/ddr3_phy_v1_4_xiphy_behav.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/phy/ddr3_phy_v1_4_xiphy.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/iob/ddr3_phy_v1_4_iob_byte.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/iob/ddr3_phy_v1_4_iob.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/clocking/ddr3_phy_v1_4_pll.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/xiphy_files/ddr3_phy_v1_4_xiphy_tristate_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/xiphy_files/ddr3_phy_v1_4_xiphy_riuor_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/xiphy_files/ddr3_phy_v1_4_xiphy_control_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/xiphy_files/ddr3_phy_v1_4_xiphy_byte_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/xiphy_files/ddr3_phy_v1_4_xiphy_bitslice_wrapper.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/ip_top/design_1_ddr3_0_0_phy.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_wtr.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ref.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_rd_wr.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_periodic.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_group.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ecc_merge_enc.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ecc_gen.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ecc_fi_xor.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ecc_dec_fix.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ecc_buf.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ecc.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_ctl.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_cmd_mux_c.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_cmd_mux_ap.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_arb_p.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_arb_mux_p.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_arb_c.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_arb_a.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_act_timer.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc_act_rank.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/controller/ddr3_v1_4_mc.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ui/ddr3_v1_4_ui_wr_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ui/ddr3_v1_4_ui_rd_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ui/ddr3_v1_4_ui_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ui/ddr3_v1_4_ui.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_ar_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_aw_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_b_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_cmd_arbiter.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_cmd_fsm.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_cmd_translator.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_fifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_incr_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_r_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_w_channel.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_wr_cmd_fsm.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_wrap_cmd.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_a_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_register_slice.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axi_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_axic_register_slice.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_carry_and.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_carry_latch_and.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_carry_latch_or.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_carry_or.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_command_fifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_comparator.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_comparator_sel.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_comparator_sel_static.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_r_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi/ddr3_v1_4_w_upsizer.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi_ctrl/ddr3_v1_4_axi_ctrl_addr_decode.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi_ctrl/ddr3_v1_4_axi_ctrl_read.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi_ctrl/ddr3_v1_4_axi_ctrl_reg_bank.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi_ctrl/ddr3_v1_4_axi_ctrl_reg.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi_ctrl/ddr3_v1_4_axi_ctrl_top.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/axi_ctrl/ddr3_v1_4_axi_ctrl_write.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/clocking/ddr3_v1_4_infrastructure.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_xsdb_bram.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_write.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_wr_byte.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_wr_bit.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_sync.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_read.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_rd_en.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_pi.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_odt.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_mc_odt.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_debug_microblaze.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_cplx_data.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_cplx.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_config_rom.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_bfifo.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_addr_decode.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_top.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal_xsdb_arbiter.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_cal.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_chipscope_xsdb_slave.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/ddr3_v1_4_dp_AB9.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top/design_1_ddr3_0_0_ddr3.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top/design_1_ddr3_0_0_ddr3_mem_intfc.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal/design_1_ddr3_0_0_ddr3_cal_riu.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top/design_1_ddr3_0_0.sv" \
  "../../../bd/design_1/ip/design_1_ddr3_0_0/tb/microblaze_mcs_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_rst_ddr3_0_266M_0/sim/design_1_rst_ddr3_0_266M_0.vhd" \
  "../../../bd/design_1/ip/design_1_rst_clk_wiz_0_100M_0/sim/design_1_rst_clk_wiz_0_100M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_lite_ipif_v3_0_4 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_pkg_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work lib_srl_fifo_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_uart16550_v2_0_30 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/7dfc/hdl/axi_uart16550_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_uart16550_0_0/sim/design_1_axi_uart16550_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_rocket_wrapper_0_0/sim/design_1_rocket_wrapper_0_0.v" \
  "../../../bd/design_1/ip/design_1_blk_mem_gen_0_0/sim/design_1_blk_mem_gen_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work generic_baseblocks_v2_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work fifo_generator_v13_2_8 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work fifo_generator_v13_2_8 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_data_fifo_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_crossbar_v2_1_29 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_xbar_0/sim/design_1_xbar_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work axi_bram_ctrl_v4_1_8 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/85f5/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_bram_ctrl_0_0/sim/design_1_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work dist_mem_gen_v8_0_13 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_fifo_v1_0_17 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/3d41/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work interrupt_control_v3_1_4 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work axi_quad_spi_v3_2_27 -V93 $xmvhdl_opts \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/3799/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../bd/design_1/ip/design_1_axi_quad_spi_0_0/sim/design_1_axi_quad_spi_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work axi_clock_converter_v2_1_27 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/29db/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_auto_cc_0/sim/design_1_auto_cc_0.v" \
  "../../../bd/design_1/ip/design_1_auto_cc_1/sim/design_1_auto_cc_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_protocol_converter_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_dwidth_converter_v2_1_28 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/08ae/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_auto_ds_0/sim/design_1_auto_ds_0.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_0/sim/design_1_auto_pc_0.v" \
  "../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
  "../../../bd/design_1/ip/design_1_auto_ds_2/sim/design_1_auto_ds_2.v" \
  "../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_mmu_v2_1_26 $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../../block_design.gen/sources_1/bd/design_1/ipshared/75b7/hdl/axi_mmu_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"$ref_dir/../../../bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"$ref_dir/../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/30ef" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/ip_1/rtl/map" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/ip_top" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ip/design_1_ddr3_0_0/rtl/cal" +incdir+"../../../../block_design.gen/sources_1/bd/design_1/ipshared/ec67/hdl" \
  "../../../bd/design_1/ip/design_1_s00_mmu_0/sim/design_1_s00_mmu_0.v" \
  "../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.design_1 xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.design_1 -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/porterlu/block_design/block_design.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log design_1_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-step]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-reset_log]\n\
Usage: design_1.sh [-keep_index]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
